version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  rest-api-incubator:
    image: rest-api-incubator:0.0.1-SNAPSHOT
    environment:
      - VIRTUAL_HOST=rest.local
      - VIRTUAL_PORT=8080